apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapRefName }}
  labels:
    app: quakewatch
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}

