version: "3.9"

services:
  quakewatch:
    build:
      context: .
      dockerfile: Dockerfile
    image: bgalit/quakewatch:1.0
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

