apiVersion: v1
kind: Service
metadata:
  name: quakewatch-svc
  namespace: quakewatch
spec:
  selector:
    app: quakewatch
  ports:
    - name: http
      port: 8000
      targetPort: 5000
  type: LoadBalancer

